### ISSUE TITLE
Unrelated property added to events

### ISSUE THREAD

**Issue by rcrivera** [segment-integrations/integration-kissmetrics#1]
Whenever I track an event, it adds by default a property name "products" to the event. I'm not tracking any data related to e-commerce, so I don't need this property at all. I think this is the [line of code](https://github.com/segmentio/integration-kissmetrics/blob/master/lib/mapper.js#L61) that's adding the property. Is there any configuration I can set to remove the "products" property from my events?

**Comment by hankim813** [comment]
Closed for inactivity/irrelevance. Please reopen if it's still an issue!
